version: 0.2

phases:
  install:
    commands:
      - echo Installing NPM dependencies
      - npm install
      - echo Install completed

artifacts:
  files:
    - '**/*'
  discard-paths: no
